FROM debian:latest

#------------Install system dependencies---------------------------
# RUN apk add curl
RUN apt update && apt install -y \
    curl \
    build-essential \
    pkg-config \
    libssl-dev \
    libwebkit2gtk-4.1-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    libjavascriptcoregtk-4.1-dev \
    libsoup-3.0-dev

#------------Ensure Rust (Rustup) is installed--------------
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
RUN chmod 100 rustup.sh
RUN ./rustup.sh -y

#------------Install nvm and use node 22--------------------
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
RUN nvm install 22
RUN nvm use 22


COPY . .

#------------------Install project dependencies--------------
RUN npm i

#------------Start tauri app---------------------------------
CMD ["npm run tauri dev"]